### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [lempiy/kottans-js-2016#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by lempiy** [comment]
https://github.com/lempiy/kottans-js-2016/blob/master/week01/lec1/habrahabr.html

**Comment by mkozhukharenko** [comment]
You forgot to wrap into section

``` html
                <h1>Спецпроэкты</h1>
                <ul>
                    <li><a href="#">Соберите свой стартап</a></li>
                    <li><a href="#">Linux в Azure</a></li>
                    <li><a href="#">Создай игру</a></li>
                </ul>
```

**Comment by mkozhukharenko** [comment]
li should be wrapped by up ol etc

``` html
                        <div class='recent-articles'>
                            <li>Уязвимость в электронном дневнике или как украсть персональные данные 2-х миллионов пользователей</li>
                            <li>Почему стоит нанимать джуниоров</li>
                            <li>Что браузеры делают с вашим JavaScript-кодом: об оптимизациях в JS-движках на примере V8</li>
                        </div>
```

**Comment by mkozhukharenko** [comment]
:worried: oh! 
there really a lot of errors! check your markup [here](https://validator.w3.org/nu)

**Comment by mkozhukharenko** [comment]
wrong use case for [dl](https://html.spec.whatwg.org/multipage/semantics.html#the-dl-element) [dd](https://html.spec.whatwg.org/multipage/semantics.html#the-dd-element) [dt](https://html.spec.whatwg.org/multipage/semantics.html#the-dt-element):

read the spec, please. 

``` html
                <dl>
                    <dt>Разделы</dt>
                    <dd>Публикации</dd>
                    <dd>Хабы</dd>
                    <dd>...</dd>
                </dl>
```

**Comment by lempiy** [comment]
made some [fixes](https://github.com/lempiy/kottans-js-2016/commit/89d529c4415549a2b439a6ebeb31ae4a6053378c#diff-59cf220a4ad050ad5dacd3f0e12fbac3). Link to current [markup](https://github.com/lempiy/kottans-js-2016/blob/master/week01/lec1/habrahabr.html). #2

**Comment by lempiy** [comment]
Added headings to all sections. [Commit](https://github.com/lempiy/kottans-js-2016/commit/c6b5eb676d6b075b01264bcdacc3f7193dd4a081#diff-59cf220a4ad050ad5dacd3f0e12fbac3). #2

**Comment by mkozhukharenko** [comment]
I you add an issue number to a commit message you get a direct link this commit from an issue. E.g. `Fixed error revealed by issue.` -> `Fixed error revealed by issue. #2`

**Comment by mkozhukharenko** [comment]
You has some indentation problems (mixed tabs and space) in you project.

**Comment by mkozhukharenko** [comment]
here is some mess:

``` html
                <section class='article-section'>
                    <header class='article-header'>
                        <time datetime="2014-12-03">3 декабря 2014 в 16:57</time>
                        <h1><a href="">Разработка</a> → Десять типичных вопросов на собеседованиях на знание HTML</h1>
                        <p><a href="">HTML</a>, <a href="">Семантика</a>, <a href="">Разработка сайтов</a></p>
                    </header>
                    <article>
                        <h2 hidden>Текст статьи</h2>
                            <!-- ТЕКСТ СТАТЬИ-->

                        <div class='article-tags'></div>
                    </article>                  
                </section>
```

You got heading and main article text in two different elements (check an outline for your markup)
check the [article](https://html.spec.whatwg.org/multipage/semantics.html#the-article-element) elemenet

**Comment by lempiy** [comment]
You mean mess in `<header>`? I should have separate tags in `<h1>` and `<p>` or what? #2

**Comment by mkozhukharenko** [comment]
``` html
article
     header
          time 3 декабря 2014 в 16:57
          h1  Десять типичных вопросов 
     div (or main)
         p ТЕКСТ СТАТЬИ
```

**Comment by lempiy** [comment]
> You got heading and main article text in two different elements (check an outline for your markup)
> check the article elemenet

I guess [fixed](https://github.com/lempiy/kottans-js-2016/blob/master/week01/lec1/habrahabr.html). #2

**Comment by mkozhukharenko** [comment]
You got me wrong about issue linking
Your commit message:

```
Fixed header.
Fixed main article header.
```

should be:

```
#2 Fixed header.
Fixed main article header.
```

**Comment by mkozhukharenko** [comment]
> I guess fixed.

much better 
Have you understood the main idea?

Minor proposal:
you dont need this element at all, do you?

``` html
    <section class='article-section'>
        <h2 hidden>Раздел статьи и ее теггов</h2>
```

**Comment by lempiy** [comment]
Not fully but i will practice more in further projects.
I forgot about this section. It has no purpose to exist after i moved header to article.

**Comment by mkozhukharenko** [comment]
you don't need to add #2 all the time. see https://github.com/lempiy/kottans-js-2016/issues/2#issuecomment-220844752

**Comment by mkozhukharenko** [comment]
[this](https://html.spec.whatwg.org/multipage/semantics.html#outline) may help you
