### ISSUE TITLE
Фидбек на домашку №2

### ISSUE THREAD

**Issue by tiny-kottan** [lempiy/kottans-js-2016#4]
`const arrayOfBootstrap = bootstrap.split('\n.');` - first line would not match this and you'll end up with ".navbar"
Possible workarounds:
1) using editor and multiple cursors of find+replace to remove first .
2) using split + map / filter
`classes.split(/\n/m).map((i) => i.replace(/^\./, ''))`
`classes.split(/\.([\w\d\-]+)\n?/).filter(i => i)`
3) being a smart and stubborn guy and using single split with regexp, keeping in mind [that](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#Description):

```
If separator is a regular expression that contains capturing parentheses, then each time separator is matched, the results (including any undefined results) of the capturing parentheses are spliced into the output array.
```

vendor requires/imports (like `require('posthtml')`) would usually/by some conventions reside at the top of your file.

`arrayOfBootstrap.indexOf(item) <> 0` -> [Array#includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

```
if (too) {
  if(much) {
    if(nesting) {
    } else {
    }
  } else {
    if(Icannoteven) {
    } else {
    }
  }
}
```

Top level if could be replaced with guard condition for negative case `if (arrayOfBootstrap.includes(class)) {return}`
Deepest level if-else could be replaced with `?:`, something like

```
let someGoodVarNameGoesHere = item.replace('js-', '')
jsData += jsData.length > 0 ? ' ' +  someGoodVarNameGoesHere : someGoodVarNameGoesHere
```

Also, you could add whitespace in any case each iteration, but just do final `.trim()`.
There's a possibly good read for you regarding refactoring conditionals. [Martin Fowler](martinfowler.com/books/refactoring.html) chapter 11 or smth.

```
arrayOfClasses.forEach(MAINLOGICGOESHERE)
```

This is a bit tangled code which performs multiple operations, might be better to have those functions separated.
Also, pattern with having accumulator, modifying it on every iteration, returning accumulator is basically [Array#reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce).
Other possible improvement - why work with strings and concatenate, if you could form array of final classes and just do `.join(' ')` on those?
And one way to get a subset of array from larger array would be `Array#filter`, for example.

`node.attrs['class'] = false;` - why do you have this assignment?

```
String.prototype.startsWith = function(letters)
{
    return(this.indexOf(letters) == 0);
};
```

this part has spaces, although other parts are using tabs for identation. Any of these are fine, but be consistent.

**Comment by lempiy** [comment]
Here is a new [version](https://github.com/lempiy/kottans-js-2016/blob/master/week01/lec2/plugin.js).

> `node.attrs['class'] = false`; - why do you have this assignment?

I need this to clear initial 'class' value of node. Otherwise, 'data-js' would just duplicate 'class' value. (in cases when node has only 'js-' classes)
