### ISSUE TITLE
Домашнее задание по промисам

### ISSUE THREAD

**Issue by tiny-kottan** [lempiy/kottans-js-2016#7]
Написать `Promise.map`, `Promise.some` и `Promise.reduce`. Должно работать как в доках блуберда: http://bluebirdjs.com/docs/api-reference.html. Тесты: https://github.com/petkaantonov/bluebird/tree/master/test/mocha
Промис нужно сабклассить. `Promise.all` не юзать. Брать конструктор промиса из this

**Comment by lempiy** [comment]
Here is my [solution](https://github.com/lempiy/kottans-js-2016/blob/master/week04/lec1/Promise.js), not sure its nice - i'm not familiar with JS tests yet :-(
